### ISSUE TITLE
Help with examples

### ISSUE THREAD

**Issue by freeman128** [contentful/ng-contentful#3]
Hello, is it possible to extend usage section with concrete examples on how to pull specific fields with angular expressions ? I managed to get certain objects from contentful (using your examples) but i'm unclear on how to nest ng-repeats in order to get single entry and its fields. 

Thank you

**Comment by janv** [comment]
First you need to load your content types and entries somewhere:

```js
ContentTypeList.loadAllContentTypes();

contentfulClient.entries().then(function(entries){
  $scope.entries = entries;
});
```

Then, to iterate over your entries:

```html
<div ng-repeat="entry in entries track by entry.sys.id" ng-controller="EntryController">
  Entry {{entryTitle()}}
  <ul>
    <li ng-repeat="field in contentType().fields track by field.id">
      {{field.name}}: {{entry.fields[field.id]}}
    </li>
  </ul>
</div>
```

I created a Plunkr using our example space: http://plnkr.co/edit/JboHnB7AgzpizfjbzuIq?p=preview

I will also add this to the readme.
